[project]
name = "today-eat-what"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.0.8",
    "langgraph>=1.0.3",
    "pydantic>=2.12.4",
    "requests>=2.32.5",
]
